# Generated by Django 3.2 on 2021-06-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_id', models.CharField(max_length=400, verbose_name='id категории')),
                ('name_product', models.CharField(max_length=400, verbose_name='Название')),
                ('price', models.CharField(max_length=400, verbose_name='Цена')),
                ('suplier_id', models.CharField(max_length=400, verbose_name='id поставщика')),
                ('photo', models.FileField(upload_to='static')),
                ('show', models.BooleanField()),
                ('data_delete', models.DateField(null=True, verbose_name='Дата удаления')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Каталог',
                'managed': True,
            },
        ),
    ]
