# Generated by Django 3.2 on 2021-06-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210613_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='static/cataliog/'),
        ),
    ]
