# Generated by Django 3.2 on 2021-06-17 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_users_position'),
        ('catalog', '0004_auto_20210614_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_delete', models.DateField(blank=True, null=True, verbose_name='Дата удаления')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person', to='users.users')),
                ('productfav', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productfav', to='catalog.catalog')),
            ],
        ),
    ]
