# Generated by Django 3.2 on 2021-06-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_catalog_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='photo',
        ),
        migrations.AddField(
            model_name='catalog',
            name='photos',
            field=models.JSONField(default='{}', verbose_name='Фотографии'),
        ),
    ]
