# Generated by Django 3.2 on 2021-06-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminId', models.CharField(blank=True, max_length=100, null=True, verbose_name='id админа')),
                ('dateProcessed', models.DateField(blank=True, null=True, verbose_name='Дата обработки')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('text', models.CharField(blank=True, max_length=400, null=True, verbose_name='Текст')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер')),
                ('name', models.CharField(blank=True, max_length=400, null=True, verbose_name='Имя')),
            ],
        ),
    ]
