# Generated by Django 3.2 on 2021-06-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210608_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='position',
            field=models.IntegerField(blank=True, choices=[(1, 'Администратор'), (2, 'Флорист'), (3, 'Курьер')], default=0, null=True, verbose_name='Должность'),
        ),
    ]
