# Generated by Django 3.2 on 2021-06-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_users_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='position',
            field=models.IntegerField(blank=True, choices=[(1, 'Администратор'), (2, 'Флорист'), (3, 'Курьер')], default=None, null=True, verbose_name='Должность'),
        ),
    ]
