# Generated by Django 3.2 on 2021-06-16 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_alter_users_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=400, null=True, verbose_name='Адрес')),
                ('dateorder', models.DateField(blank=True, null=True, verbose_name='Дата заказа')),
                ('datedelivery', models.DateField(blank=True, null=True, verbose_name='Дата доставки')),
                ('datepay', models.DateField(blank=True, null=True, verbose_name='Дата оплаты')),
                ('sum', models.CharField(blank=True, max_length=200, null=True, verbose_name='Цена')),
                ('status', models.IntegerField(blank=True, choices=[(1, 'Обработан'), (2, 'Доставлен')], default=None, null=True, verbose_name='Статус')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('data_delete', models.DateField(blank=True, null=True, verbose_name='Дата удаления')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='users.users')),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courier', to='users.users')),
                ('florist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='florist', to='users.users')),
            ],
        ),
    ]
