# Generated by Django 3.2 on 2021-06-18 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_favorite'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='product_id',
        ),
        migrations.AddField(
            model_name='reviews',
            name='catalog_r',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalog_r', to='catalog.catalog'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='name_client',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='review_text',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Текст'),
        ),
    ]
