# Generated by Django 3.2 on 2021-06-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20210619_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='data',
            field=models.DateField(blank=True, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='data_delete',
            field=models.DateField(blank=True, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='static/main/image'),
        ),
    ]
